Create: modeling
wecode-bootcamp-korea/30-1st-YumYumFruit-backend pull request #1
Opened 2022-03-01 10:55 UTC by kkookkss

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- users, products, orders app 생성 및 모델링 완료

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. app 생성
  - users
  - products
  - orders

2. 모델작성 및 마이그레이션 완료
  - users
  - products
  - orders

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 모델 작성시에 _id를 안 붙여도 되는 점을 다시 한번 깨닫게 되었습니다.
- 장고 컨벤션에 의해 CharField에는 NULL=True 사용을 지양하고 blank=True를 이용해 빈 문자열을 정의하는 점을 알게 되었습니다. 

<br />

## :: 기타 질문 및 특이 사항

2022-03-01 12:44 UTC, jamessoun93 requested changes

2022-03-01 12:44 UTC, jamessoun93 commented on orders/models.py
> +    user         = models.ForeignKey(User, on_delete=models.CASCADE)
가격 정보 같은경우 우리나라 통화의 경우 INTEGER로 처리가 가능하지만, 달러 혹은 유로같은 글로벌 화폐를 생각해보면 소수점 두자리까지 필요한 경우가 많고, 가격이라는 필드 특성상 이런 글로벌 통화 표기 규칙을 따라주시면 좋아서 Decimal 필드를 활용해주시는게 좋습니다.

2022-03-01 12:44 UTC, jamessoun93 commented on products/models.py
> +    price          = models.IntegerField()
여기도 마찬가지입니다!

2022-03-01 12:44 UTC, jamessoun93 commented on products/models.py
> +    thumb_image    = models.CharField(max_length=200)
```suggestion
    thumbnail_image_url    = models.CharField(max_length=200)
```
데이터베이스 테이블명 및 컬럼명은 혼선은 방지하기 위해 줄이지 않고 있는 그대로 지정해주시는 걸 추천드립니다. 워낙 예민한 정보이고 추후 여러개의 서비스와 연결되어 사용할수도 있게 되는 부분이라서요.

2022-03-01 12:44 UTC, jamessoun93 commented on products/models.py
> +    iamge      = models.CharField(max_length=200)
```suggestion
    image_url      = models.CharField(max_length=200)
```

2022-03-01 14:47 UTC, kkookkss commented
- 예치금, 적립금 등 가격 관련된 필드 수정 완료
- 필드명 수정 완료
- Decimal_Field max_digits 추가 완료

2022-03-02 02:24 UTC, jamessoun93 approved these changes
LGTM

2022-03-02 02:24 UTC, merged