[이예솔]Create: products app >> ProductListView with pagination, sorting, filtering
wecode-bootcamp-korea/30-1st-YumYumFruit-backend pull request #3
Opened 2022-03-03 06:29 UTC by wingna1

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- ProductListView 생성 : 상품 리스트 페이지 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 리스트 페이지
- sort를 GET으로 받아 order_by 설정
- category를 GET으로 받아 filter 설정 
- category가 all일 경우 전체 상품 출력

2. Paging 기능 구현
- limit와 offset을 계산해 paging 기능 구현
- 리스트 데이터와 전체 페이지 수, 해당 카테고리의 데이터 수 리턴

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- paginator를 사용했는데, 해당 기능이 template로 render되어 사용하지 못하게 되었고, limit와 offset을 계산하여 직접 페이징 기능을 구현하게 되었습니다.
- 정렬 기능이 재미있어 보였는데 order_by로 생각보다 간단하게 구현되었고, 해당 데이터를 프론트와 상의하여 입력받자 잘 작동하였습니다.

<br />

## :: 기타 질문 및 특이 사항
- paginator로 JsonResponse에 전달할 수 있는 방법은 없을까요? 직접 하는 방법도 좋지만 django의 기능을 사용해 보고 싶은데 JsonResponse에 전달하는 방법을 찾지 못했습니다.
- Paginator사용한 부분 일단 프론트와 상의하기 전에 작성한 post 메서드에 남겨 두었는데, 수정 후 paginator를 사용하거나 삭제하려고 합니다.

2022-03-07 09:01 UTC, jamessoun93 requested changes

2022-03-07 09:01 UTC, jamessoun93 commented on products/urls.py
> +    path("/list", ProductListView.as_view()),
어제 restful api 배우셨죠? `list` 가 굳이 필요할까요?
`GET http://localhost:8000/products` 만 가지고도 충분히 의미파악이 가능합니다.

2022-03-07 09:01 UTC, jamessoun93 commented on products/views.py
> +                product_list   = Product.objects.all()
```suggestion
            q = Q()
            
            if category != "all" :
                q &= Q(category_id=category)
                
            product_list = Product.objects.filter(q)
```

2022-03-07 09:01 UTC, jamessoun93 commented on products/views.py
> +                                    "total_items":total_items
```suggestion
                                    "products"    :product_offset,
                                    "total_number_of_pages":page_count,
                                    "total_count":total_items
```

2022-03-07 09:01 UTC, jamessoun93 commented on products/views.py
> +            category  = request.GET.get("category", "all")
```suggestion
            category_id  = request.GET.get("category", "all")
```

2022-03-07 09:01 UTC, jamessoun93 commented on products/views.py
> +            return JsonResponse({"results":"INVALID_PARAMETER"}, status=400)
-

2022-03-07 11:01 UTC, wingna1 commented
- 변수명 수정 완료
- urls.py 수정 완료
- category_validator 리스트 활용
- Q객체 활용

2022-03-08 02:26 UTC, jamessoun93 approved these changes

2022-03-08 02:26 UTC, merged